name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  
    - run: docker login -usampath853@gmail.com webpages.jfrog.io -p AKCp8mZwKi3nDGJYMkm1hvwQmLovDBLz1H3AhJQg2RzzwDFRE3ZGHLt3uiKnmu2DLEScfbm7h
    - run: docker build tag webpages.jfrog.io/webpages-docker-local/webpage .
    - run: docker push webpages.jfrog.io/webpages-docker-local/webpage

